name: flapkap_flutter_challenge
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-262.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc:
  bloc:
  sizer: ^2.0.15
  intl: ^0.17.0
  responsive_framework: ^0.1.5
  gradient_widgets: ^0.6.0
  syncfusion_flutter_charts: ^19.3.48

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/